# Generated by Django 4.2.29 on 2026-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('IFU', 'IFU'), ('SOP', 'SOP'), ('CER', 'CER'), ('RMF', 'RMF'), ('LABEL', 'Labeling')], max_length=10),
        ),
    ]
